exclude: 'variables.ini'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 526904b1596ea461616a7b8b20ebd959454b57fc
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.8.0
    hooks:
    - id: pyupgrade
